[build]
  builder = "nixpacks"
  buildCommand = "prisma generate && npm run build"
  watchPatterns = ["src/**", "prisma/**", "package.json"]

[deploy]
  startCommand = "npm start"
  healthcheckPath = "/api/health"
  healthcheckTimeout = 300
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 10

[environments.production]
  variables = { NODE_ENV = "production" }